apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio-sensor
  namespace: {{ .Release.Namespace }}
spec:
  dependencies:
    - eventName: video
      eventSourceName: minio
      name: test-dep
  loggingFields: null
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
    - template:
        k8s:
          name: workflow-trigger
          operation: create
          parameters:
            - dest: spec.arguments.parameters.1.value
              src:
                dataKey: notification.0.s3.object.key
                dependencyName: test-dep
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: video-processing-
              spec:
                arguments:
                  parameters:
                    - name: bucket
                      value: video-pipeline
                    - name: key
                      value: key
                entrypoint: video-processing
                serviceAccountName: operate-workflow-sa
                templates:
                  - name: video-processing
                    steps:
                      - - name: downsizing
                          template: downsizing
                  - container:
                      args:
                        - '-i'
                        - /tmp/video.mp4
                        - '-vf'
                        - scale=320:240
                        - /tmp/reduced.mp4
                      image: jrottenberg/ffmpeg:3-scratch
                    inputs:
                      artifacts:
                        - name: video
                          path: /tmp/video.mp4
                          s3:
                            accessKeySecret:
                              key: accesskey
                              name: artifacts-minio
                            bucket: '{{"{{"}}workflow.parameters.bucket{{"}}"}}'
                            endpoint: {{ .Values.minio.url }}
                            insecure: true
                            key: '{{"{{"}}workflow.parameters.key{{"}}"}}'
                            secretKeySecret:
                              key: secretkey
                              name: artifacts-minio
                    name: downsizing
                    outputs:
                      artifacts:
                        - name: video
                          path: /tmp/reduced.mp4
                          archive:
                            none: {}
                          s3:
                            accessKeySecret:
                              key: accesskey
                              name: artifacts-minio
                            bucket: '{{"{{"}}workflow.parameters.bucket{{"}}"}}-processed'
                            endpoint: {{ .Values.minio.url }}
                            insecure: true
                            key: '{{"{{"}}workflow.parameters.key{{"}}"}}'
                            secretKeySecret:
                              key: secretkey
                              name: artifacts-minio
        name: video-processing

