apiVersion: v1
kind: Secret
metadata:
  name: artifacts-minio
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  accesskey: {{ .Values.minio.accessKey | b64enc }}
  secretkey: {{ .Values.minio.secretKey | b64enc }}